### ISSUE TITLE
Permissions Error

### ISSUE THREAD

**Issue by livefromblessings-pc** [busyloop/lolcat#100]
New to command line stuff and I have a mighty need for rainbow output, but when I do

`gem intall lolcat`

I get this error:

>  "You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory."

How do I fix this, I am the root user of this comp (I think) so I should have all permissions. I have conda/anaconda installed, is this messing it up? I'd also like to set rainbow output as the default, is that possible?

Thanks for helping in 2019...

**Comment by m-o-e** [comment]
Hi! :)

You may have to do `sudo gem install lolcat`.
However, a better way to install on OSX is via [homebrew](https://brew.sh).
(just follow the install instructions on that page, then afterwards you can `brew install lolcat`)

Unfortunately there is no easy way to make rainbow output the default everywhere.
The world is not ready for that, yet. But you can append `| lolcat` to any command
that outputs text and include that in scripts as well.

**Comment by livefromblessings-pc** [comment]
Ahhh ok, that would too powerful..... well thank you so much for the help, my scripts are gonna be so obnoxious now buahahahahahaha🦄🌈!
