### ISSUE TITLE
Tabs not displaying as expected

### ISSUE THREAD

**Issue by EvansWinner** [busyloop/lolcat#101]
I have a slightly odd environment, so it might be that. It is Windows 10, Cygwin, Mintty, zsh (also tested with Bash).

This is the first time I've opened an issue on Github, Don't know if the screenshot will work....I don't know much about Ruby, so... forgive me if it's not helpful.

![image](https://user-images.githubusercontent.com/916340/66867605-dc147700-ef58-11e9-8327-08c7b6d94125.png)

**Comment by alexmyczko** [comment]
column -t test | lolcat

**Comment by EvansWinner** [comment]
I am not sure what the purpose of that is. Yes, that culumnizes all the text, but that's not quite the issue. It doesn't address lolcat's actual tab handling. 

But trying it now, some time later on a different machine (similar Cygwin environment) it works as expected, preserving the tabs. So this can probably be closed.

![image](https://user-images.githubusercontent.com/916340/88853170-8e49c200-d1ac-11ea-8cb4-c749463ca10f.png)
