### ISSUE TITLE
Apt installation method to readme.md

### ISSUE THREAD

**Issue by dotlineX** [busyloop/lolcat#106]
Hi, could you please add the APT package manager installation method.

`apt install lolcat`

**Comment by m-o-e** [comment]
We have something even better now!

Try `sudo snap install lolcat`

And please make noise in case it doesn't work 😋

**Comment by vlas-sokolov** [comment]
Making noise - snap works but lots of folks would rather go either the gem route or the apt way - can readme include some alternatives for installation? Snap has lots of people [unconvinced](https://news.ycombinator.com/item?id=23052108).

**Comment by m-o-e** [comment]
Problem with the alternative routes is that they 
don't work reliably which results in user frustration.

The politics around snap are annoying, but for this type
of utility it's the least bad distribution method amongst the
currently available options.

Advanced users are of course free to install in any way they like
but for the time being the only officially supported method is snap.

**Comment by winkee01** [comment]
@m-o-e I don't like snap, it installed too many unnecessary things, at least you should provide another option for me to install it besides snap.
