### ISSUE TITLE
MacOS lolcat coloring is not working - fresh install of Monterey

### ISSUE THREAD

**Issue by ButchAnton** [busyloop/lolcat#132]
$ brew install lolcat
$ lolcat --help
Spews escape codes rather than colorized help.

I've tried with iterm2, terminal, alacritty, and hyper.  I have not changed any settings for terminal or alacritty.  This is a fresh installation of Monterey (12.0.1).

**Comment by ButchAnton** [comment]
This seems to be a problem with zsh.  The Monterey installed version of zsh is 5.8, as is the most recent version available via homebrew.  If I exec bash or tcsh, lolcat --help works just fine.

**Comment by Vritrahan** [comment]
Can you please describe how you fixed it? I am facing the same issue.
