### ISSUE TITLE
Bad help url

### ISSUE THREAD

**Issue by WHK102** [busyloop/lolcat#133]
In help message says: `Report lolcat bugs to <http://www.github.org/busyloop/lolcat/issues>` , but github.com not www.github.org.

**Comment by m-o-e** [comment]
That was fixed very long ago. Update your lolcat.


https://github.com/busyloop/lolcat/pull/23

**Comment by yhojann-cl** [comment]
But i use latest official package from apt:

```
whk@machine:~$ lolcat -v
lolcat 42.0.99 (c)2011 moe@busyloop.net
whk@machine:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

**Comment by m-o-e** [comment]
Looks like the package hasn't been updated in a long time.
These package are not maintained by the lolcat foundation.

You can try installing with `snap` for a newer version.

But using older versions is of course also fine - it may just not have the latest bugfixes.
