### ISSUE TITLE
Not working with all unicode characters

### ISSUE THREAD

**Issue by M4urice** [busyloop/lolcat#35]
Does not fully support utf-8 encoded files (characters). Tested with this file http://pastebin.com/MVp3Dz5x and got the following error: 

    > cat utf.txt | lolcat
    /Library/Ruby/Gems/2.0.0/gems/lolcat-42.1.0/lib/lolcat/lol.rb:45:in `gsub!': invalid byte sequence in UTF-8 (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/lolcat-42.1.0/lib/lolcat/lol.rb:45:in `println'
	from /Library/Ruby/Gems/2.0.0/gems/lolcat-42.1.0/lib/lolcat/lol.rb:36:in `block in cat'
	from /Library/Ruby/Gems/2.0.0/gems/lolcat-42.1.0/lib/lolcat/lol.rb:34:in `each_line'
	from /Library/Ruby/Gems/2.0.0/gems/lolcat-42.1.0/lib/lolcat/lol.rb:34:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/lolcat-42.1.0/lib/lolcat/lol.rb:34:in `cat'
	from /Library/Ruby/Gems/2.0.0/gems/lolcat-42.1.0/lib/lolcat/cat.rb:113:in `block in cat!'
	from /Library/Ruby/Gems/2.0.0/gems/lolcat-42.1.0/lib/lolcat/cat.rb:107:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/lolcat-42.1.0/lib/lolcat/cat.rb:107:in `cat!'
	from /Library/Ruby/Gems/2.0.0/gems/lolcat-42.1.0/bin/lolcat:25:in `<top (required)>'
	from /usr/bin/lolcat:23:in `load'
	from /usr/bin/lolcat:23:in `<main>'

**Comment by m-o-e** [comment]
That's because your input is not valid utf-8.

```shell
$ curl -s http://pastebin.com/MVp3Dz5x | iconv -f UTF-8 -o /dev/null
iconv: illegal input sequence at position 10255
```
