### ISSUE TITLE
this software makes my life better.

### ISSUE THREAD

**Issue by linked** [busyloop/lolcat#36]
literally every day.

please fix it.

**Comment by linked** [comment]
![screenshot 2015-07-04 14 46 01](https://cloud.githubusercontent.com/assets/395107/8509490/77a3cba0-225b-11e5-8945-0ead4771a213.png)

bbbbbbbenchmarks!

**Comment by linked** [comment]
![screenshot 2015-07-04 14 56 53](https://cloud.githubusercontent.com/assets/395107/8509535/f8b2f3a0-225c-11e5-84b9-7d7c38429539.png)

dddddddddddddevops!

**Comment by linked** [comment]
<img width="837" alt="screenshot 2015-07-04 15 06 02" src="https://cloud.githubusercontent.com/assets/395107/8509558/3a418736-225e-11e5-898a-ac3551a8585f.png">

sssssssssssscience!

**Comment by m-o-e** [comment]
Thanks ;)
