### ISSUE TITLE
Invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by EmptyStackExn** [busyloop/lolcat#38]
Hello,
I have installed and have no problem using `lolcat` on my Linux system. However, on my Mac OS X, when I connect via SSH to my Linux machine, I cannot properly use `lolcat` and get the following error 

![screenshot from 2015-08-11 13 55 55](https://cloud.githubusercontent.com/assets/1613250/9197051/59bd2610-4031-11e5-8baf-9053cd7b1d13.png)

**Comment by m-o-e** [comment]
This is a locale issue which can unfortunately be a bit tedious to debug.

Please compare the output of the `locale` command when logged into your Linux box locally
-vs- when ssh'd in. The difference between the two outputs is causing your problem.

Your OSX ssh is either not forwarding the local OSX locale
or forwarding a blank locale, which then defaults to "C" aka US-ASCII
on the linux side. In consequence Ruby chokes on the first non-ascii
character in your `ls`-output.

Long story short: You need to ensure your shell environment is set to a locale
that supports your non-ascii characters (`en_US.UTF-8` is what most people use).

Here a (very) basic locales primer and a StackOverflow question discussing the
various ways to enforce a remote locale with ssh.

* http://perlgeek.de/en/article/set-up-a-clean-utf8-environment
* http://askubuntu.com/questions/144235/locale-variables-have-no-effect-in-remote-shell-perl-warning-setting-locale-f 

Hope this helps, good luck!

**Comment by EmptyStackExn** [comment]
Thanks for your answer. I now understand the issue. Indeed, the host machine (Linux) has the following locale
```
LANG=en_US.UTF-8
LANGUAGE=en
LC_CTYPE="en_US.UTF-8"
LC_ALL=
...
```
And yet, the guest machine (OS X) has the following
```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```
