### ISSUE TITLE
unable to package lolcat on a distribution level (depending on specific outdated versions)

### ISSUE THREAD

**Issue by anthraxx** [busyloop/lolcat#40]
Hey,

currently it is impossible to package lolcat properly on a distribution level, as it has a hard dependency to paint 0.8.6 and trollop 1.16.2.
Please don't enforce specific trollop and paint version, this is needed as its not possible to ship lolcat on a distribution level. To be able to ship lolcat as a distribution package, it needs to be compatible with paint 1.0.0 and trollop 2.1.2.

Can you please adjust the gemspec accordingly? (Not sure if there is any code change required or both libs remained API compatible)

Once this is resolved I plan to package your software into the repositories :smile:

**Comment by anthraxx** [comment]
I have made some tests and changing "~>" to ">=" seems to work fine for my test cases. It seems lolcat is totally compatible with pain 1.0.0 and trollop 2.1.2 :+1:

**Comment by anthraxx** [comment]
wow, that was fast :smile: :+1: :fireworks: :sunglasses:

**Comment by m-o-e** [comment]
I have upgraded the deps and pushed a new gem version.

However, please note that lolcat will not normally update its
dependencies unless they break or introduce critical bug-fixes.

If your distributions package manager can not handle pinned
dependencies then it should refrain from packaging ruby gems
and rather focus on ensuring that `gem install` works as expected.

Here's the explanation why ">=" is a bad idea:
http://yehudakatz.com/2010/08/21/using-considered-harmful-or-whats-wrong-with/

**Comment by anthraxx** [comment]
its known I'm not stupid. It's still a good thing for an application to also support the newest versions of the libraries that it uses. Its not the problem of the package manager, it can pin versions properly... but that means having lolcat installed forces libraries at a specific version. Which is a no-go (especially in Arch Linux) as we always ship the most current version.
It was a major upgrade of both versions, to be technically precise also ~> can break if the developers are careless and change the API (which of cause they shouldn't)
and using a global 'gem install' (with dependencies) is a no-go in the systemwide distribution level of package handling as it installs and handles dependencies by its own, bypassing the package management fully. I guess you know the problem between ruby gems and distribution level of packaging!
I can't see how its bad when a piece of software is compatible with the most current major versions rather then using stone old libraries from 2013 (or in other cases maybe even older). Technically its (was) using an ancient, out-dated and dead-end version of libraries (which i personally consider harmful :grin: )
I know how ruby and rubygems work and don't misinterprete this as blaming, finger pointing or personal critics, but normally if a software should get shipped on a distribution level (in Arch Linux) then its suposed to work with the most current versions of its depending libraries, if its not the case then its a bug (from Arch Linux point of view) as we generally try not to ship old major versions separately but try to push the topic that everything should work with the most current version. If you want to see lolcat in this distribution then it requires to run with the most current major versions of its dependencies, sorry. Also my personal view is that every proper software should be agnostic to its dependencies and try to be compatible with the most currently shipped versions (personal packager, developer and also security related opinion).

still: funny and great software :yum: hope you have a nice weekend and also hope you will understand our points and hope future major upgrades of your dependencies won't be a hassle
