### ISSUE TITLE
Top Output doesn't refresh properly

### ISSUE THREAD

**Issue by ahnospell44** [busyloop/lolcat#46]
Top is printing out formatting characters and the refresh is showing whole new pages every time. 
![image](https://cloud.githubusercontent.com/assets/7912525/15162411/c19abd6c-16d0-11e6-9f57-69fdd6ec22bc.png)

**Comment by m-o-e** [comment]
That is normal behavior. `top` sends ANSI control characters for cursor positioning
and colors that lolcat needs to strip to function; the result of these efforts is what you are seeing.

You can approximate a more familiar top view with a small script, like so:

`while true; do clear; top -b | head -n 30 | lolcat; sleep 5; done`
