### ISSUE TITLE
Nice Tool!

### ISSUE THREAD

**Issue by systemroot** [busyloop/lolcat#47]
but is an problem. 
try to execute this as bash script
> echo ""
> echo "blablabla"
> sleep 0.5
> clear
> echo ""
> echo ""
> echo "blablabla"
> sleep 0.5
> clear
> echo ""
> echo ""
> echo ""
> echo "blablabla"
> sleep 0.5
> clear
> echo ""
> echo ""
> echo ""
> echo ""
> echo "blablabla"
> sleep 0.5
> clear

Now try ./script.sh
then ./script.sh | lolcat

"clear" isn't working :/
![](http://image.prntscr.com/image/0c2e873203d744c6929851d740086cf8.png)

I'm Using Ubuntu 14.04

**Comment by ohenepee** [comment]
What was the solution?

**Comment by systemroot** [comment]
@ohenepee  haven't found it.

**Comment by ohenepee** [comment]
The re-open the issue... you don't close issues until a solution have been found or the repo's owner deems the issue unworthy

**Comment by m-o-e** [comment]
Hi guys,

lolcat works on the input character by character and strips
ANSI escape sequences (such as the one for "clear screen"),
because supporting them would make things very complicated.

Perhaps you could separate the clear from the lolcat output like this:

```
echo "Hello" | lolcat
sleep 5
clear
echo "World" | lolcat
```

Hope that helps!

**Comment by systemroot** [comment]
@m-o-e thank you for explain now i understand
