### ISSUE TITLE
Adding a formula for lolcat to homebrew

### ISSUE THREAD

**Issue by AnimiVulpis** [busyloop/lolcat#55]
Do you think it would be possible for you to create a formula like explained here: https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md

If not. Do you give your permission that someone else might create a formula on your behalf?

**Comment by m-o-e** [comment]
While I love homebrew I don't think it makes
sense to provide formulas for ruby gems.

It's just another level of indirection that can
break and tends to become notoriously outdated.

What's wrong with `sudo gem install lolcat`,
which should work on any vanilla OSX?

**Comment by AnimiVulpis** [comment]
It would be more convenient for me.
I have no clue about ruby and gems.

The only thing I don't like about your suggestions is the `sudo` part.
That was never necessary for me with homebrew.

It seems to me, that homebrew already contains formulas that are basically ruby gems, but I might be wrong.

Is this an example of a gem that is used in homebrew?
#### Formula:
https://github.com/Homebrew/homebrew-core/blob/7dfe465b7cb48be58bedc4349a5357953a53133e/Formula/ghi.rb  
#### Repository containing gem:  
https://github.com/stephencelis/ghi

I think it would greatly increase the visibility of your nice little tool.

_But if you don't want to maintain that formula would you mind if I try to add it to homebrew (somewhen in the next weeks)?_

**Comment by m-o-e** [comment]
Well, if this is an example then it is a bad one.

It has a specific version number hardcoded (line 4) and even
references a Ruby dependency (line 11) which means:

* The formula doesn't automatically update with upstream, the hardcoded version number has to be changed

* A brew install may conflict with a regular install in unforeseen ways

* The "brewified" gem dependency (`pygments.rb`) suffers from all the same problems and is almost guaranteed to break over time

Package manager inception is an anti-pattern, don't do it.
It's the reason why distro bundled Ruby and Python packages are always outdated and broken.

OSX and all relevant Linux distros ship with Ruby out of the box.
`sudo gem install lolcat` should work everywhere without any problems or surprises.

For further illustration of the problem also see the lolcat debian package:
* https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=lolcat;dist=unstable

While I appreciate the effort of everyone involved, it is ultimately doing the community a disservice.
The Debian versions is now six(!) years out of date and effectively devolved into a fork.

**Comment by AnimiVulpis** [comment]
Didn't knew about those problems.

Then I will roll with the gem instead. 
Is there a tutorial explaining how to keep Ruby gems up-to-date and/or make it work without `sudo`?

**Comment by m-o-e** [comment]
Don't know about a tutorial but you can re-run `sudo gem install lolcat` at any time
and it will always update to the latest version, if there is one.
