### ISSUE TITLE
lolcat does not work on binary files

### ISSUE THREAD

**Issue by themightyoarfish** [busyloop/lolcat#58]
It appears `lolcat` only works on utf-8-encoded files. E.g. running `lolcat /bin/cat` results in 
```
/Library/Ruby/Gems/2.0.0/gems/lolcat-42.24.0/lib/lolcat/lol.rb:53:in `gsub!': invalid byte sequence in UTF-8 (ArgumentError)
```

This problem was posted here before, but I am not sure how this does not relate to lolcat. Is it intended to only work with utf-8?

**Comment by m-o-e** [comment]
Yes, it is intended to work with text.

If you really want to lolcat a binary then
the rainbow council recommends: `hexdump /bin/cat | lolcat`
