### ISSUE TITLE
Consider adding official man page?

### ISSUE THREAD

**Issue by whereswaldon** [busyloop/lolcat#59]
Not a big deal, obviously, but it'd be nice if this project had a man page. Debian has written [one](https://packages.debian.org/jessie/all/lolcat/filelist) for it, but distributions that pull directly from source (like Arch) don't have that because it isn't actually part of the project release files.

**Comment by m-o-e** [comment]
lolcat bad at writing documentation (take very long time, no fingers, just paws). PR welcome.

**Comment by mathieu-aubin** [comment]
PR Up - Hopefully does it for you.

**Comment by m-o-e** [comment]
Merged. Thank you and sorry for taking so long.
