### ISSUE TITLE
Misalignment

### ISSUE THREAD

**Issue by Faboor** [busyloop/lolcat#60]
When running `$ apt-get upgrade | lolcat` the text gets misaligned for some reason. Included screenshot:
![image](https://cloud.githubusercontent.com/assets/12911864/26791726/e5510b8a-4a0f-11e7-8dc2-f3c5c9df8b85.png)

**Comment by m-o-e** [comment]
Try this: `apt-get upgrade | grep -v '\r' | lolcat`

Lolcat gets confused by the CRs that apt-get uses for its status messages.

**Comment by asottile** [comment]
Depending on the application, I instead needed:

```bash
.... | sed 's/\r//g' | lolcat
```
