### ISSUE TITLE
uncat like behavior

### ISSUE THREAD

**Issue by Thepiggy** [busyloop/lolcat#63]
Type this into your terminal:
```while true; do echo -n $RANDOM | cat; done```
The output is as expected, now type this into your terminal
```while true; do echo -n $RANDOM | lolcat; done```
As you can see lolcat is putting everything on a new line

**Comment by benknoble** [comment]
Moving `lolcat` to the end of the loop as in `for a in {1..10}; do echo -n $RANDOM; done | lolcat` produces output on one line, with trailing newline.

Using `cat` (`for a in {1..10}; do echo -n $RANDOM; done | cat`) produces output on one line _sans_ trailing newline.
