### ISSUE TITLE
Cowsay command not working (Homebrew)

### ISSUE THREAD

**Issue by Harps13** [busyloop/lolcat#64]
When using lolcat via homebrew (MacOS), cowsay doesn't seem to work. I am using it in this context:

cowsay "Hi" | lolcat

Is that right?

**Comment by Harps13** [comment]
Maybe I'm just bad at this. :P

**Comment by Harps13** [comment]
Nevermind. Turns out I had to additionally install cowsay. Clearly cowsay is built into the apt-get version of lolcat and not the homebrew version.

**Comment by m-o-e** [comment]
```
 ______________________________________
/ i am not part of lolcat. you have to \
\ install me separately.               /
 --------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```
https://github.com/schacon/cowsay

**Comment by Harps13** [comment]
Wow, I really am an idiot.
