### ISSUE TITLE
Feature request - forward exit code of previous program

### ISSUE THREAD

**Issue by davidaramant** [busyloop/lolcat#72]
It would be nice if there were an option to use the return code of the previous program, so that (for example) `really-long-build | lolcat` would return a failure code if the build failed.

The `really-long-build` is out of our hands. We've actually found that piping the output to lolcat makes the errors stand out more (since stderr is not recolored) 😄

**Comment by m-o-e** [comment]
You don't need lolcat to pass that through.
Shells already have the handy `$PIPESTATUS` and `pipefail`
for exactly this purpose :)

https://unix.stackexchange.com/questions/14270/get-exit-status-of-process-thats-piped-to-another

**Comment by davidaramant** [comment]
Whoops, yeah, I didn't even check if it was possible before I posted this.  Apparently an app receiving data over a pipe _can't_ get the exit code of the previous program, anyway.
