### ISSUE TITLE
rbenv + Debian package + #!/usr/bin/env ruby = LoadError

### ISSUE THREAD

**Issue by rlue** [busyloop/lolcat#76]
I'm running rbenv on a Debian machine and just installed lolcat with `sudo apt install lolcat`.

```
$ lolcat foo
Traceback (most recent call last):
        2: from /usr/games/lolcat:21:in `<main>'
        1: from /home/rlue/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/home/rlue/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- lolcat/version (LoadError)
```

This happens because of the hashbang line at the top of the `lolcat` executable; if I change it to `#!/usr/bin/ruby`, then everything works.

Is there any way that the Debian package for lolcat could be modified to use the system ruby?

**Comment by m-o-e** [comment]
I'm not involved with the deb package at all but agree;
not changing the hashbang line in the pkg seems like
a questionable decision.

I don't know if this is just an oversight or a Debian policy.
It might be worth filing a bug on the Debian bugtracker.

Unfortunately there's nothing we can do here directly
to fix it for everyone. For your own machine, as you probably know,
you can fix it by doing a `gem install lolcat` within your rbenv environment.

**Comment by rlue** [comment]
Whoops, good point. Looks like [it's been in the Debian bug tracking system since 2016](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836206) — guess I won't hold my breath.

(I take it that means you don't know who's responsible for maintaining the lolcat Debian package?)

**Comment by m-o-e** [comment]
Yep that's right, lolcat does not release any official distro packages
- all packages that you may find are made by 3rd parties.

The packaging of ruby gems has traditionally been a sad story on most
linux distros (lolcat isn't the only gem suffering from this).

Whenever possible I'd suggest to stick with rbenv.

**Comment by utkarsh2102** [comment]
Hi @rlue @m-o-e,
Too bad that no one seemed to care about this until now, but as I've stepped over to maintain lolcat only recently (a couple of days ago), I've fixed this in the latest version, that is, 100.0.1-3.

Please let me know if I can help you in any other way and sorry that no one could get this fixed so far :)

**Comment by m-o-e** [comment]
@utkarsh2102 Thanks a lot for taking care of this! 🙇 

> Please let me know if I can help you in any other way

Actually there would be something, in case you're interested. 😬 
This ticket has been backlogged for far too long:
https://github.com/busyloop/lolcat/pull/83

Having a snap package would be amazing (ideally one that
automatically updates itself when a new git tag is pushed to
this repo).

Since snap is (afaik) available on almost all distros we could then
ask all pkg-maintainers to change their packages to point the snap-version,
for a unified install experience on all platforms.

**Comment by utkarsh2102** [comment]
Hello,

Hm, I am not sure if I can pull this off. As much as I want to help, I am not aware of snap packaging.
Please let me know if you need **any** help from the Debian side though.

**Comment by m-o-e** [comment]
Hi, thanks a lot for the support, much appreciated! :)

I think the fix that you made to the deb was all
that's needed. I haven't tried myself but it _should_
work properly now also in the presence of a ruby
version manager such as rbenv/rvm.

Snap is also solved; we have a snap-pkg and it's listed
as the recommended install method in the README.

So all should be good in lolcat-land for now. 🌈

**Comment by utkarsh2102** [comment]
Hi @m-o-e,

> Snap is also solved; we have a snap-pkg and it's listed
as the recommended install method in the README.

Wow, that's super awesome! :heart: 

Thanks for your continuous work on this! :100: :rocket:
