### ISSUE TITLE
Add option to support line number printing

### ISSUE THREAD

**Issue by meskarune** [busyloop/lolcat#77]
In the regular GNU cat program it has the option `-n` to show line numbers. Maybe its possible to add to lolcat.

**Comment by m-o-e** [comment]
I agree, lolcat should have all features of regular cat.

Unfortunately I won't have time to work on this any time soon, but PRs are welcome!

**Comment by meskarune** [comment]
If you keep this open I can try and work on something if/when I get free time, otherwise maybe someone else will see this as a chance to jump in.

**Comment by dread-uo** [comment]
Like this?

![image](https://user-images.githubusercontent.com/7685154/45663419-b3634900-badc-11e8-9c15-35fc3124d80b.png)

**Comment by dread-uo** [comment]
Would it look like this?

![image](https://user-images.githubusercontent.com/7685154/45794310-63b38780-bc6c-11e8-82a9-8baeb9688a41.png)

**Comment by meskarune** [comment]
> Would it look like this?

That seems fine to me honestly

**Comment by JohnAZoidberg** [comment]
This feature was removed in 2074d47238520f44931bd0204947f6acdc489f7a.
What exactly was broken?

**Comment by m-o-e** [comment]
It didn't account for the buffering, so it would break after 4kb of input.

**Comment by dread-uo** [comment]
Oops... I'll take a look at it this weekend
