### ISSUE TITLE
Broken output when used with sl

### ISSUE THREAD

**Issue by ZaWertun** [busyloop/lolcat#78]
Screen recording with the bug: https://vimeo.com/286163200
SL (Steam Locomotive) sources can be found there: https://github.com/mtoyoda/sl.

**Comment by ZaWertun** [comment]
`lolcat --version`
lolcat 99.9.11 (c)2011 moe@busyloop.net

**Comment by m-o-e** [comment]
Thanks for the report. This has already been fixed.
Please upgrade to lolcat 99.9.19
