### ISSUE TITLE
Report Bug, Home Page URL from lolcat -h using ".org" instead of ".com"

### ISSUE THREAD

**Issue by gvitalie** [busyloop/lolcat#79]
> # [*  :santa:](https://gvitalie.github.io/linus.torvalds.emo/)

> ### Report Bug, Home Page URL from lolcat -h using ".org" instead of ".com"

![](https://lh3.googleusercontent.com/HkX-jGVzB2uTuOazWDYNmDydx3Npzas43j9c-yN2at_XcbCJk1cx1inm5_jEMb_3RCx2c46xhezfKt84UIvpWg2QvGv_aXu-Z4CmHlg8xAAWxQuKCLlbPCapAnqEwVknxzsMaqhuBeg=w610-h488-no)   

#### Thank You, Dear Friend, LolCat! ![](http://static.skaip.org/img/emoticons/180x180/f6fcff/cat.gif)  

_Note: Clicking on image below will open an YouToBee video_
[![](https://img.youtube.com/vi/_0uGQBWksPA/maxresdefault.jpg)](https://www.youtube.com/watch?v=_0uGQBWksPA)  

> # [*  :santa:](https://gvitalie.github.io/linus.torvalds.emo/)

> https://gvitalie.github.io/linus.torvalds.emo/

**Comment by m-o-e** [comment]
Thank you for the report, this has already been fixed very long ago. :)
If you upgrade to a newer lolcat version you will see the correct URL.
