### ISSUE TITLE
Backspace after lolcat.

### ISSUE THREAD

**Issue by Aniket-Pradhan** [busyloop/lolcat#84]
Hello There.

I am running Arch Linux with Ruby version 2.5.3p105, and bash v4.4.23. I was trying out lolcat but I figured a small bug-ish.

While using lolcat with Bash, it identifies my backspace as "\b" (^H) key. This does not occur when I am using another shell, like fish. Although "\b" corresponds to the backspace key, it does not actually go back, but prints "\b" instead.

To reproduce the same, try pressing the backspace key after entering any command with lolcat (like, `ls | lolcat`).

I am not sure if this issue should be raised here, or at bash.

**Comment by andersonentwistle** [comment]
Same issue, after running lolcat in bash on Debian the backwards-delete key for bash gets mapped to printing "^H". Definitely need advice. Have to logout and reopen to change mapping back.

**Comment by Aniket-Pradhan** [comment]
[This](https://stackoverflow.com/a/47763404/8726146) might help.

Maybe we can do something about this issue. I'll dig in further.

**Comment by m-o-e** [comment]
Sorry, can not reproduce this. 

Can you try running this command: `stty sane -istrip <&1`

This is what lolcat runs before exiting, in order to cleanup your terminal.
When you run it directly (without lolcat), does it also mess up your backspace-key?

**Comment by Aniket-Pradhan** [comment]
Yes. Running the above command directly messes the backspace key.

**Comment by m-o-e** [comment]
Ok, how about this shorter command: `stty sane <&1`

Does that also mess up your terminal? 🤔

**Comment by Aniket-Pradhan** [comment]
Yep. That too.

Re-configuring the backspace after this command seems to work (i.e. using `stty erase '^H'`.

As an example:
```
┌─[major@archlinux]─[~]
└──╼ $ stty sane <&1
┌─[major@archlinux]─[~]
└──╼ $ ls^H
bash: $'ls\b': command not found
┌─[✗]─[major@archlinux]─[~]
└──╼ $ stty erase '^H'
┌─[major@archlinux]─[~]
└──╼ $ l
bash: l: command not found
```

**Comment by m-o-e** [comment]
This is rather strange. What terminal emulator are you using?
Could you try a different one (e.g. `xterm`, `gnome-terminal` or similar)
to see if the problem also occurs there?

When you look at `man stty` and search for `sane` you can see that
this command is actually meant to _fix_ issues such as the one that you
describe, rather than create them.

@Grimy 
The above `stty`-call was introduced by your [PR](https://github.com/busyloop/lolcat/pull/68/files#diff-f6526226b2e55e59d8628207a0409da9R63) in 2018.
Did you add it for a specific reason or only as a general safeguard?
I wonder if we can just drop it or if that might cause other problems. 🤔

**Comment by Aniket-Pradhan** [comment]
> When you look at `man stty` and search for `sane` you can see that this command is actually meant to _fix_ issues.

I agree. Even I don't know why it is not working in this case. I had tried using it, but it didn't work. In the end, I had to resort to manually reset it.

I am currently using the UXterm emulator. This problem also persists in xterm. However, there's no such issue in gnome-terminal and terminator. It's probably something related to the xterm family, I guess.

**Comment by m-o-e** [comment]
I'll give it a week to see if Grimy has an opinion on this and otherwise remove the `stty`-call.

**Comment by andersonentwistle** [comment]
For reference the setup I am using to get this strange problem is definitely unique. This problem does not occur when I use lolcat on my WSL with Debian. I was running it on my Raspberry Pi (Raspbian GNU 9, a version of Debian) over SSH on MobaXTerm. Bash version 4.4.12 and Ruby version 2.3.3p222.

**Comment by Grimy** [comment]
`stty sane` is meant to fix these issues, but it does so by setting backspace to what it *thinks* is the right value, and of course nobody can ever agree on what the right value is for backspace (`^H` or `^?`).

Note that I didn’t introduce the `stty` call, I just replaced `stty cooked -nl` (which can badly mess up non-ASCII characters) with `stty sane -istrip`. I think it would be safe to completely remove the `stty` call. Or, to be more conservative, replace it with `stty -nl echo`, which still does some sanitizing but without touching backspace or 8th bits.

**Comment by m-o-e** [comment]
@Grimy
Thanks for chiming in so quickly!
I've release a new version with the `stty` call removed.

@Aniket-Pradhan @andersonentwistle
Please let us know in case you still experience any problems with the latest version. 🍭
