### ISSUE TITLE
python3 - lolcat 

### ISSUE THREAD

**Issue by arlidge** [busyloop/lolcat#87]
Hello - I have a script in python3 where I am requiring user input.

in the script I have this line : 

name = input('What is your name ') 

When I pipe the script to lolcat - python3 name.py | lolcat

The text "What is your name" does not appear. It is just blank. I can still continue with the required input and then the output is all lolcat. 

I can also solve with a print("What is your name") above the input

Without lolcat it functions normally. 

Please advise.

**Comment by m-o-e** [comment]
Rather than piping your script into lolcat you may want to
call out to lolcat (via `subprocess` module) from inside your script,
capture the output and print it to the screen.

Sorry, can not provide more detailed scripting support here.
