### ISSUE TITLE
[feature idea] - HTML output

### ISSUE THREAD

**Issue by pillepalle1** [busyloop/lolcat#91]
The idea is to introduce a switch `--html` 
 which, instead of generating colored output, generates html code, 
  which, if interpreted by a browser, shows what lolcat prints on the console if invoked normally

**Comment by m-o-e** [comment]
Nah, the resulting HMTL would be huge and inefficient.
Better to do that kind of thing in javascript.

**Comment by therealmaxmoon** [comment]
I would be interested in colorized ASCI art and tried to do something like the following:

`figlet utopify.org | lolcat | ansi2html > index.html`

But the output is not colorized. 

Does someone have a solution yet?
