### ISSUE TITLE
Unable to generate gemspec file.

### ISSUE THREAD

**Issue by discapes** [busyloop/lolcat#93]
Trying to emerge lolcat on Gentoo gives the following error: 
[emerge -tv lolcat](http://dpaste.com/0FS332H.txt)

**Comment by m-o-e** [comment]
Looks like the ebuild can't find _git_:

`-e:1:in `eval': No such file or directory - git (Errno::ENOENT)`

Might be possible to fix with `emerge git` - but not sure.
This is a Gentoo/ebuild bug, not a lolcat issue.

**Comment by discapes** [comment]
> Looks like the ebuild can't find _git_:
> 
> `-e:1:in 'eval': No such file or directory - git (Errno::ENOENT)`
> 
> Might be possible to fix with `emerge git` - but not sure.
> This is a Gentoo/ebuild bug, not a lolcat issue.
works! Ty
