### ISSUE TITLE
neofetch | lolcat returns weird output

### ISSUE THREAD

**Issue by discapes** [busyloop/lolcat#94]
![lolcat](https://user-images.githubusercontent.com/48839377/57585692-2601b880-74f4-11e9-8f15-770cf8d42f6e.png)
Also happens in Konsole

**Comment by nikolalukovic** [comment]
The same in regular gnome terminal on pop_os
![Screenshot from 2019-06-02 01-53-06](https://user-images.githubusercontent.com/6897673/58754878-6e9c0880-84d9-11e9-8306-73e629c1a815.png)

**Comment by m-o-e** [comment]
Works with current lolcat version.
Please ensure `lolcat --version` prints `lolcat 99.9.69`.

**Comment by Ranem1993** [comment]
https://github.com/busyloop/lolcat/issues/94
