### ISSUE TITLE
lolcat vs ruby/gem issue

### ISSUE THREAD

**Issue by wildbi111** [busyloop/lolcat#95]
I installed lolcat (99.9.69) on Fedora 30 using 'gem install lolcat' and it works when run as root, but as a normal user it fails with this error:

Traceback (most recent call last):
        2: from /usr/local/bin/lolcat:23:in `<main>'
        1: from /usr/share/rubygems/rubygems.rb:302:in `activate_bin_path'
/usr/share/rubygems/rubygems.rb:283:in `find_spec_for_exe': can't find gem lolcat (>= 0.a) with executable lolcat (Gem::GemNotFoundException)

**Comment by wildbi111** [comment]
I don't knew if I figured out a fix or workaround.  But copying the .gem directory created by the 
"gem install lolcat" command to each users home dir and changing owner.group has resolved the program.  If there is a better way of doing this please let me know.

**Comment by m-o-e** [comment]
Fyi, lolcat can now be install with snap.

`sudo snap install lolcat`

**Comment by ahillio** [comment]
I'm so glad `sudo gem install lolcat` is an option.  Love the colors!

**Comment by ernstki** [comment]
> but as a normal user it fails with this error `[…] can't find gem lolcat (>= 0.a) with executable lolcat (Gem::GemNotFoundException)`

For those who find themselves here after doing a web search for this error message, I suggest having a look at the values of `GEM_PATH` and `GEM_HOME`. Try `unset`ting both of them and see if you get a different result.

ref.: https://bbs.archlinux.org/viewtopic.php?pid=1831370#p1831370
