### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by talishka** [busyloop/lolcat#97]
I'm using lolcat on all my linux boxes, but now i'm having this behaviour and i don't know why

My motd is coloring ok when i login, but i get no spaces and a bunch of codes. I'm using it with the -f parameter like i do on all my linuxes. When i use screenfetch it works ok, the problem arises with neofetch.

Lemme show you: https://ibb.co/zmth4N4

**Comment by m-o-e** [comment]
What command did you use to produce the above output?
