### ISSUE TITLE
colorization not working properly in v99.9.99

### ISSUE THREAD

**Issue by incomingstick** [busyloop/lolcat#99]
Some time in the last update or two the way colors are displayed must have changed that does not seem to format correctly.

I can test two versions of lolcat side by side, and have included a screenshot to show an example. Unfortunately I have 0 Ruby experience, otherwise I would try and solve the issue right away. I will  be looking to do some research on building gems when I have time, but wanted this documented in the meantime, as it may be some time before I can do that. In the image below, the terminal on the left is my local Arch Linux machine, and the terminal on the right is an ssh session to a remote Ubuntu 19.04 Hyper-V Virtual Machine. The exact command run in both terminals is: `neofetch && fortune | cowsay | lolcat && lolcat -v`

System info and lolcat versions are in the screenshot, but I have included the details here for your convenience:

Local OS:  Arch Linux x86_64
Kernel Version: 5.2.8
Lolcat Version: v99.9.99

Remote OS: Ubuntu 19.04 x86_64
Kernel Version: 5.0.0
Lolcat version: v42.0.99

![image](https://user-images.githubusercontent.com/11799068/62838483-6cc19480-bc42-11e9-997f-f5c1a870becc.png)

**Comment by m-o-e** [comment]
This is rather odd, the same command works fine for me on OSX.

Does it work for you when you leave out the neofetch and just do
`fortune | cowsay | lolcat && lolcat -v`?

Also what happens when you run v99.9.99 on the Ubuntu host?
(I suspect there might be a problem with the Arch version 🤔)

**Comment by incomingstick** [comment]
I thought it very odd as well. When running it with out neofetch, the behavior is still the same. I did just upgrade the remote version to v99.9.99 and it does still seem to display correctly. Here is a screenshot with the updates:

![image](https://user-images.githubusercontent.com/11799068/62839034-3ab43080-bc4a-11e9-89ef-1f7ed54d4831.png)

I think you are correct that perhaps it is an issue with my Arch version, but I cannot think of what else may have changed that could cause this 🤔 feel free to close this I guess, and I will just continue diggin into my arch system🤷‍♂️

**Comment by incomingstick** [comment]
I wanted to follow up, as I found a reddit post from just a day or two ago that I strongly suggest a maintainer take a look at, just to stay looped in.

https://www.reddit.com/r/archlinux/comments/cnvlsa/lolcat_colors_glitched_only_at_urxvt/

**Comment by m-o-e** [comment]
@incomingstick 
Thanks a lot for reporting this and for pointing to the Reddit thread! 🙇 
It is now [fixed](https://github.com/busyloop/lolcat/commit/7d96dcad726a5efa05a45b8729be9b6d851437ab), please let me know if you still experience any problems with the latest version.
